WITH EVIDENCIAS AS (
    SELECT ID AS ID_TAREFA, 'TEXTO' AS TIPO_EVIDENCIA, EVIDENCIAS AS CONTEUDO, DATA_ULTIMA_ATUALIZACAO, DW_INGESTED_AT
    FROM {{ ref('stg_tarefa') }} WHERE NULLIF(TRIM(EVIDENCIAS), '') IS NOT NULL
    UNION ALL
    SELECT ID, 'COMMIT', EVIDENCIA_COMMIT_SHA, DATA_ULTIMA_ATUALIZACAO, DW_INGESTED_AT
    FROM {{ ref('stg_tarefa') }} WHERE NULLIF(TRIM(EVIDENCIA_COMMIT_SHA), '') IS NOT NULL
    UNION ALL
    SELECT ID, 'ANEXO', EVIDENCIA_ANEXO, DATA_ULTIMA_ATUALIZACAO, DW_INGESTED_AT
    FROM {{ ref('stg_tarefa') }} WHERE NULLIF(TRIM(EVIDENCIA_ANEXO), '') IS NOT NULL
)
SELECT
    HASH('EVIDENCIA', ID_TAREFA, TIPO_EVIDENCIA, CONTEUDO)      AS SK_EVIDENCIA,
    HASH('TAREFA', ID_TAREFA)                                  AS SK_TAREFA,
    ID_TAREFA,
    TIPO_EVIDENCIA,
    CONTEUDO                                                    AS CONTEUDO_ORIGINAL,
    REGEXP_REPLACE(CONTEUDO, '<[^>]+>', ' ')                   AS CONTEUDO_SEM_HTML,
    LENGTH(CONTEUDO)                                            AS QUANTIDADE_CARACTERES,
    REGEXP_COUNT(TRIM(CONTEUDO), '\\S+')                      AS QUANTIDADE_PALAVRAS,
    REGEXP_COUNT(LOWER(CONTEUDO), 'https?://')                  AS QUANTIDADE_URLS,
    IFF(REGEXP_LIKE(LOWER(CONTEUDO), '\\.(png|jpg|jpeg|gif|webp|bmp|svg)(\\?|$)'), TRUE, FALSE) AS FL_IMAGEM,
    IFF(TIPO_EVIDENCIA = 'COMMIT', TRUE, FALSE)                 AS FL_COMMIT,
    REGEXP_SUBSTR(LOWER(CONTEUDO), '\\.(png|jpg|jpeg|gif|webp|bmp|svg|pdf|docx?|xlsx?|zip)(\\?|$)', 1, 1, 'e', 1) AS EXTENSAO_ARQUIVO,
    DATA_ULTIMA_ATUALIZACAO,
    DW_INGESTED_AT                                              AS DT_CARGA
FROM EVIDENCIAS
