-- KPI: Erro médio absoluto (Number) = média de |HET_MAX - HORAS_EXECUTADAS|
SELECT
    ROUND(AVG(ABS(r.HET_MAX - f.HORAS_EXECUTADAS)), 2) AS ERRO_MEDIO_ABSOLUTO
FROM MUNKA_GOLD.FCT_TAREFA f
JOIN MUNKA_GOLD.DIM_REGRA r ON r.SK_REGRA = f.SK_REGRA
LEFT JOIN MUNKA_GOLD.DIM_PROJETO p ON p.SK_PROJETO = f.SK_PROJETO
WHERE f.HORAS_EXECUTADAS IS NOT NULL
  AND r.HET_MAX IS NOT NULL
  [[AND {{complexidade}}]]
  [[AND {{periodo}}]]
