-- KPI: Total de horas realizadas (Number)
-- Fonte: MUNKA_GOLD.FCT_TAREFA.HORAS_EXECUTADAS
SELECT
    ROUND(SUM(f.HORAS_EXECUTADAS), 1) AS HORAS_REALIZADAS
FROM MUNKA_GOLD.FCT_TAREFA f
JOIN MUNKA_GOLD.DIM_REGRA r ON r.SK_REGRA = f.SK_REGRA
LEFT JOIN MUNKA_GOLD.DIM_PROJETO p ON p.SK_PROJETO = f.SK_PROJETO
WHERE f.HORAS_EXECUTADAS IS NOT NULL
  AND r.HET_MAX IS NOT NULL
  [[AND {{complexidade}}]]
  [[AND {{periodo}}]]
