-- Gráfico: contagem de tarefas por tipo de evidência técnica extraída (features de entrada do modelo)
SELECT 'Tem Codigo' AS EVIDENCIA, SUM(TEM_CODIGO) AS QTD FROM MUNKA_ML.ML_TAREFA_FEATURES
UNION ALL
SELECT 'Tem SQL', SUM(TEM_SQL) FROM MUNKA_ML.ML_TAREFA_FEATURES
UNION ALL
SELECT 'Tem Commit/Git', SUM(TEM_COMMIT) FROM MUNKA_ML.ML_TAREFA_FEATURES
UNION ALL
SELECT 'Tem Pull Request', SUM(FL_TEM_PULL_REQUEST) FROM MUNKA_ML.ML_TAREFA_FEATURES
UNION ALL
SELECT 'E Bugfix', SUM(FL_IS_BUGFIX) FROM MUNKA_ML.ML_TAREFA_FEATURES
ORDER BY QTD DESC
