-- Gráfico: quantidade de tarefas que envolvem cada área técnica (features de contexto do modelo)
SELECT 'Frontend' AS AREA, SUM(FL_ENVOLVE_FRONTEND) AS QTD FROM MUNKA_ML.ML_TAREFA_FEATURES
UNION ALL
SELECT 'Backend', SUM(FL_ENVOLVE_BACKEND) FROM MUNKA_ML.ML_TAREFA_FEATURES
UNION ALL
SELECT 'Dados', SUM(FL_ENVOLVE_DADOS) FROM MUNKA_ML.ML_TAREFA_FEATURES
ORDER BY QTD DESC
