-- Tabela de apoio — Top 15 tarefas com maior score de qualidade de evidência
SELECT
    TAREFA_ID,
    NOME_TAREFA,
    NOME_PROJETO,
    NOME_COMPLEXIDADE,
    SCORE_QUALIDADE_EVIDENCIA,
    HORAS_EXECUTADAS,
    TOTAL_UST
FROM MUNKA_ML.ML_TAREFA_FEATURES
WHERE SCORE_QUALIDADE_EVIDENCIA IS NOT NULL
ORDER BY SCORE_QUALIDADE_EVIDENCIA DESC
LIMIT 15
