-- Gráfico: score médio de qualidade da evidência e horas médias executadas, por complexidade
SELECT
    NOME_COMPLEXIDADE AS COMPLEXIDADE,
    ROUND(AVG(SCORE_QUALIDADE_EVIDENCIA), 2) AS SCORE_MEDIO,
    ROUND(AVG(HORAS_EXECUTADAS), 2) AS HORAS_MEDIAS
FROM MUNKA_ML.ML_TAREFA_FEATURES
GROUP BY NOME_COMPLEXIDADE
ORDER BY SCORE_MEDIO DESC
