SELECT
    ID,
    FATOR_COMPLEXIDADE,
    CARGO_ID,
    NIVEL_ID,
    CONTRATO_ID,
    ATIVO,
    ID_FATOR_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_fator_complexidade_ust') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
