SELECT
    ID,
    SERVICO_ID,
    COMPLEXIDADE_ID,
    CARGO_ID,
    NIVEL_ID,
    HET_MAX,
    DESATIVADA,
    ID_REGRA_OLD,
    FATOR_AJUSTE,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_regra') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
