SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    ATIVO,
    UST_VALOR,
    UST_CONTRATADAS,
    UST_ADITIVADAS,
    DEDUCOES_HORAS,
    DEDUCOES_UST,
    OUTROS_HORAS,
    OUTROS_UST,
    DATA_INICIO,
    DATA_FIM,
    DATA_VIGENCIA,
    UNIDADE_ADM_ID,
    FATURAR_HPA,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_contrato') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
