SELECT
    ID,
    NULLIF(TRIM(FIRST_NAME), '') AS FIRST_NAME,
    NULLIF(TRIM(LAST_NAME), '') AS LAST_NAME,
    NULLIF(TRIM(USERNAME), '') AS USERNAME,
    NULLIF(TRIM(EMAIL), '') AS EMAIL,
    REGISTRATION_DATE,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_ab_register_user') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
