SELECT
    ID,
    NIVEL_SUPERIOR_ID,
    NIVEL_INFERIOR_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_nivel_superior') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
