SELECT
    ID,
    AUTOR_ID,
    TAREFA_ID,
    NULLIF(TRIM(CONTEUDO), '') AS CONTEUDO,
    HORARIO,
    UNIDADE_ADM_ID,
    ID_COMENTARIO_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_comentario') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
