SELECT
    NULLIF(TRIM(VERSION_NUM), '') AS VERSION_NUM,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_alembic_version') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY VERSION_NUM ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
