SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    UNIDADE_SUPERIOR_ID,
    UNIDADE_EXECUTANTE_ID,
    UNIDADE_ADM_ID,
    DATA_SOLICITACAO,
    NULLIF(TRIM(LINK_GIT), '') AS LINK_GIT,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    NULLIF(TRIM(LINK_HOMOLOG), '') AS LINK_HOMOLOG,
    NULLIF(TRIM(LINK_PROD), '') AS LINK_PROD,
    NULLIF(TRIM(INF_ADICIONAL), '') AS INF_ADICIONAL,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_produto') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
