SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    NULLIF(TRIM(ENDERECO), '') AS ENDERECO,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_origem') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
