SELECT
    ID,
    DATA_INICIO,
    DATA_FIM,
    NULLIF(TRIM(OBJETIVOS), '') AS OBJETIVOS,
    COORDENACAO_ID,
    NULLIF(TRIM(DESCRICAO_CURTA), '') AS DESCRICAO_CURTA,
    ID_SPRINT_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM {{ source('munka_raw', 'raw_sprint') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1
