{{ config(
    materialized='table',
    schema='munka_ml',
    tags=['ml', 'retrospective', 'analysis']
) }}

WITH source_data AS (
    SELECT * FROM {{ ref('analise_retrospectiva') }}
)

SELECT
    CAST(TAREFA_ID AS VARCHAR(255)) AS TAREFA_ID,
    CAST(FONTE_DADOS AS VARCHAR(50)) AS FONTE_DADOS,
    
    -- Valores Reais e Estimados
    CAST(HORAS_EXECUTADAS AS FLOAT) AS HORAS_EXECUTADAS,
    CAST(HORAS_ESTIMADAS_SKLEARN AS FLOAT) AS HORAS_ESTIMADAS_SKLEARN,
    CAST(HORAS_ESTIMADAS_NUMPY AS FLOAT) AS HORAS_ESTIMADAS_NUMPY,
    
    -- Erros - Scikit-Learn
    CAST(ERRO_SKLEARN AS FLOAT) AS ERRO_SKLEARN,
    CAST(ERRO_ABSOLUTO_SKLEARN AS FLOAT) AS ERRO_ABSOLUTO_SKLEARN,
    CAST(ERRO_QUADRATICO_SKLEARN AS FLOAT) AS ERRO_QUADRATICO_SKLEARN,
    CAST(ERRO_PERCENTUAL_SKLEARN AS FLOAT) AS ERRO_PERCENTUAL_SKLEARN,
    
    -- Erros - NumPy
    CAST(ERRO_NUMPY AS FLOAT) AS ERRO_NUMPY,
    CAST(ERRO_ABSOLUTO_NUMPY AS FLOAT) AS ERRO_ABSOLUTO_NUMPY,
    CAST(ERRO_QUADRATICO_NUMPY AS FLOAT) AS ERRO_QUADRATICO_NUMPY,
    CAST(ERRO_PERCENTUAL_NUMPY AS FLOAT) AS ERRO_PERCENTUAL_NUMPY,
    
    -- Comparativo entre Modelos
    CAST(DIFERENCA_MODELOS AS FLOAT) AS DIFERENCA_MODELOS,
    CAST(MODELO_MAIS_PROXIMO AS VARCHAR(50)) AS MODELO_MAIS_PROXIMO,
    
    -- Metadados e Auditoria
    CAST(MODEL_SCOPE AS VARCHAR(100)) AS MODEL_SCOPE,
    CAST(FEATURE_SET_NAME AS VARCHAR(100)) AS FEATURE_SET_NAME,
    CAST(DATA_ANALISE AS TIMESTAMP_NTZ) AS DATA_ANALISE,
    CURRENT_TIMESTAMP() AS DATA_CARGA_SNOWFLAKE
FROM source_data
