name: munka_warehouse
version: '1.0.0'
config-version: 2

profile: munka_warehouse

model-paths: ["models"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_database: "DRAGON_DB"
  raw_schema: "MUNKA_RAW"

models:
  munka_warehouse:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: munka_stg
    intermediate:
      +materialized: view
      +schema: munka_int
    marts:
      gold:
        +materialized: table
        +schema: munka_gold
      ml:
        +materialized: table
        +schema: munka_ml