#profiles.yml
munka_warehouse:
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT', 'sfedu02-gfb24387') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE', 'DRAGON_DB') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PATH', '/opt/airflow/dags/rsa_key.p8') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE', 'TRAINING_ROLE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA', 'MUNKA_RAW') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER', 'DRAGON') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'DRAGON_WH') }}"
    prod:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT', 'sfedu02-gfb24387') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE', 'DRAGON_DB') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PATH', '/opt/airflow/dags/rsa_key.p8') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE', 'TRAINING_ROLE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA', 'MUNKA_RAW') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER', 'DRAGON') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'DRAGON_WH') }}"
  target: dev
