#profiles.yml
default:
  outputs:
    dev:
      account: sfedu02-gfb24387 #change for your account
      database: DRAGON_DB
      private_key_path: "rsa_key.p8"
      role: TRAINING_ROLE
      schema: JM
      threads: 1
      type: snowflake
      user: DRAGON
      warehouse: DBT_WH
  target: dev
  
