USE DATABASE DRAGON_DB;
USE SCHEMA MUNKA_STG;

-- ============================================================================
-- 3. CAMADA STAGING
-- ============================================================================
-- Deduplica pela chave primária da origem e mantém o registro mais recente.
-- Campos textuais vazios são convertidos para NULL.

CREATE OR REPLACE VIEW STG_AB_PERMISSION AS
SELECT
    ID,
    NULLIF(TRIM(NAME), '') AS NAME,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_PERMISSION
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_PERMISSION_VIEW AS
SELECT
    ID,
    PERMISSION_ID,
    VIEW_MENU_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_PERMISSION_VIEW
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_PERMISSION_VIEW_ROLE AS
SELECT
    ID,
    PERMISSION_VIEW_ID,
    ROLE_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_PERMISSION_VIEW_ROLE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_REGISTER_USER AS
SELECT
    ID,
    NULLIF(TRIM(FIRST_NAME), '') AS FIRST_NAME,
    NULLIF(TRIM(LAST_NAME), '') AS LAST_NAME,
    NULLIF(TRIM(USERNAME), '') AS USERNAME,
    NULLIF(TRIM(EMAIL), '') AS EMAIL,
    REGISTRATION_DATE,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_REGISTER_USER
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_ROLE AS
SELECT
    ID,
    NULLIF(TRIM(NAME), '') AS NAME,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_ROLE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_USER AS
SELECT
    ID,
    NULLIF(TRIM(FIRST_NAME), '') AS FIRST_NAME,
    NULLIF(TRIM(LAST_NAME), '') AS LAST_NAME,
    NULLIF(TRIM(USERNAME), '') AS USERNAME,
    ACTIVE,
    NULLIF(TRIM(EMAIL), '') AS EMAIL,
    LAST_LOGIN,
    LOGIN_COUNT,
    FAIL_LOGIN_COUNT,
    CREATED_ON,
    CHANGED_ON,
    CREATED_BY_FK,
    CHANGED_BY_FK,
    CARGO_ID,
    NIVEL_ID,
    COORDENACAO_ID,
    JORNADA_SEMANAL,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_USER
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_USER_ROLE AS
SELECT
    ID,
    USER_ID,
    ROLE_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_USER_ROLE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AB_VIEW_MENU AS
SELECT
    ID,
    NULLIF(TRIM(NAME), '') AS NAME,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AB_VIEW_MENU
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_AJUSTE AS
SELECT
    ID,
    DATA_INICIO,
    DATA_FIM,
    NULLIF(TRIM(TIPO), '') AS TIPO,
    UST_VALOR,
    UST_CONTRATADAS,
    CONTRATO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_AJUSTE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_ALEMBIC_VERSION AS
SELECT
    NULLIF(TRIM(VERSION_NUM), '') AS VERSION_NUM,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_ALEMBIC_VERSION
QUALIFY ROW_NUMBER() OVER (PARTITION BY VERSION_NUM ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_ANEXOS AS
SELECT
    ID,
    PROJETO_ID,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    NULLIF(TRIM(ARQUIVO), '') AS ARQUIVO,
    HORARIO,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_ANEXOS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_CARGO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    FATURAVEL,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_CARGO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_CENARIO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    PONTUACAO,
    REQUISITO_ID,
    CENARIO_PADRAO,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_CENARIO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_COMENTARIO AS
SELECT
    ID,
    AUTOR_ID,
    TAREFA_ID,
    NULLIF(TRIM(CONTEUDO), '') AS CONTEUDO,
    HORARIO,
    UNIDADE_ADM_ID,
    ID_COMENTARIO_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_COMENTARIO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_COMPLEXIDADE AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    PONTUACAO_MAIOR_QUE,
    PONTUACAO_MENOR_QUE,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_COMPLEXIDADE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_CONTRATO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    ATIVO,
    UST_VALOR,
    UST_CONTRATADAS,
    UST_ADITIVADAS,
    DEDUCOES_HORAS,
    DEDUCOES_UST,
    OUTROS_HORAS,
    OUTROS_UST,
    DATA_INICIO,
    DATA_FIM,
    DATA_VIGENCIA,
    UNIDADE_ADM_ID,
    FATURAR_HPA,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_CONTRATO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_CONTRATOS_USUARIOS AS
SELECT
    ID,
    USUARIO_ID,
    CONTRATO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_CONTRATOS_USUARIOS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_COORD_PROJETO AS
SELECT
    ID,
    PROJETO_ID,
    COORDENACAO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_COORD_PROJETO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_COORDENACAO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    NULLIF(TRIM(COR), '') AS COR,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_COORDENACAO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_ETIQUETA AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    NULLIF(TRIM(COR), '') AS COR,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_ETIQUETA
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_FATOR_COMPLEXIDADE_UST AS
SELECT
    ID,
    FATOR_COMPLEXIDADE,
    CARGO_ID,
    NIVEL_ID,
    CONTRATO_ID,
    ATIVO,
    ID_FATOR_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_FATOR_COMPLEXIDADE_UST
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_FATURA AS
SELECT
    ID,
    DATA_INICIO,
    DATA_FIM,
    DATA_CRIACAO,
    CONTRATO_ID,
    ID_FATURA_OLD,
    REAJUSTE_ID,
    RENOVACAO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_FATURA
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_FICHA_INDICADOR AS
SELECT
    ID,
    NULLIF(TRIM(TITULO), '') AS TITULO,
    GUIA_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_FICHA_INDICADOR
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_FICHAS_PROJETOS AS
SELECT
    ID,
    PROJETO_ID,
    FICHA_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_FICHAS_PROJETOS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_LIDER_PROJETOS AS
SELECT
    ID,
    PROJETO_ID,
    AB_USER_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_LIDER_PROJETOS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_NIVEL AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_NIVEL
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_NIVEL_SUPERIOR AS
SELECT
    ID,
    NIVEL_SUPERIOR_ID,
    NIVEL_INFERIOR_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_NIVEL_SUPERIOR
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_OBJETIVO AS
SELECT
    ID,
    NULLIF(TRIM(NUMERO), '') AS NUMERO,
    NULLIF(TRIM(TITULO), '') AS TITULO,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_OBJETIVO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_ORIGEM AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    NULLIF(TRIM(ENDERECO), '') AS ENDERECO,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_ORIGEM
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_ORIGENS_PROJETO AS
SELECT
    ID,
    PROJETO_ID,
    ORIGEM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_ORIGENS_PROJETO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_PRODUTO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    UNIDADE_SUPERIOR_ID,
    UNIDADE_EXECUTANTE_ID,
    UNIDADE_ADM_ID,
    DATA_SOLICITACAO,
    NULLIF(TRIM(LINK_GIT), '') AS LINK_GIT,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    NULLIF(TRIM(LINK_HOMOLOG), '') AS LINK_HOMOLOG,
    NULLIF(TRIM(LINK_PROD), '') AS LINK_PROD,
    NULLIF(TRIM(INF_ADICIONAL), '') AS INF_ADICIONAL,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_PRODUTO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_PROJETO AS
SELECT
    ID,
    UNIDADE_SUPERIOR_ID,
    UNIDADE_ADM_ID,
    DATA_SOLICITACAO,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    NULLIF(TRIM(NOME), '') AS NOME,
    PRODUTO_ID,
    NULLIF(TRIM(ABRANGENCIA), '') AS ABRANGENCIA,
    NULLIF(TRIM(ACESSO), '') AS ACESSO,
    NUMERO_SEI,
    DATA_PROTOTIPO,
    NULLIF(TRIM(LINK_PROTOTIPO), '') AS LINK_PROTOTIPO,
    DATA_DESENV,
    NULLIF(TRIM(LINK_DESENV), '') AS LINK_DESENV,
    DATA_HOMOLOG,
    DATA_PROD,
    STATUS_ID,
    PROGRESSO,
    NULLIF(TRIM(OBS_PROGRESSO), '') AS OBS_PROGRESSO,
    NULLIF(TRIM(JUSTIFICATIVA), '') AS JUSTIFICATIVA,
    INATIVO,
    DATA_PREVISAO_INICIO,
    DATA_PREVISAO_TERMINO,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_PROJETO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_PROJETO_RESULTADO_CHAVE AS
SELECT
    ID,
    PROJETO_ID,
    RESULTADO_CHAVE_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_PROJETO_RESULTADO_CHAVE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_REAJUSTE AS
SELECT
    ID,
    DATA_INICIO,
    DATA_FIM,
    UST_VALOR,
    CONTRATO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_REAJUSTE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_REGRA AS
SELECT
    ID,
    SERVICO_ID,
    COMPLEXIDADE_ID,
    CARGO_ID,
    NIVEL_ID,
    HET_MAX,
    DESATIVADA,
    ID_REGRA_OLD,
    FATOR_AJUSTE,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_REGRA
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_RENOVACAO AS
SELECT
    ID,
    DATA_INICIO,
    DATA_FIM,
    UST_CONTRATADAS,
    CONTRATO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_RENOVACAO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_REQUISITO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_REQUISITO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_RESULTADO_CHAVE AS
SELECT
    ID,
    OBJETIVO_ID,
    NULLIF(TRIM(NUMERO), '') AS NUMERO,
    NULLIF(TRIM(TITULO), '') AS TITULO,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_RESULTADO_CHAVE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_SERVICO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    NULLIF(TRIM(ESCOPO), '') AS ESCOPO,
    NULLIF(TRIM(ENTREGAVEIS), '') AS ENTREGAVEIS,
    NULLIF(TRIM(ATIVIDADES), '') AS ATIVIDADES,
    FATURAVEL,
    CONTRATO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_SERVICO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_SPRINT AS
SELECT
    ID,
    DATA_INICIO,
    DATA_FIM,
    NULLIF(TRIM(OBJETIVOS), '') AS OBJETIVOS,
    COORDENACAO_ID,
    NULLIF(TRIM(DESCRICAO_CURTA), '') AS DESCRICAO_CURTA,
    ID_SPRINT_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_SPRINT
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_STATUS AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    ORDEM,
    MOSTRAR_QUADRO,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_STATUS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_TAREFA AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    NULLIF(TRIM(DESCRICAO), '') AS DESCRICAO,
    CARGO_ID,
    NIVEL_ID,
    RESPONSAVEL_ID,
    DATA_INICIO,
    DATA_FIM,
    ETIQUETA_ID,
    PROJETO_ID,
    PRODUTO_ID,
    NULLIF(TRIM(TIPO), '') AS TIPO,
    NULLIF(TRIM(NUM_HELPDESK), '') AS NUM_HELPDESK,
    SPRINT_ID,
    REGRA_ID,
    STATUS_ID,
    HORAS_EXECUTADAS,
    NULLIF(TRIM(EVIDENCIAS), '') AS EVIDENCIAS,
    NULLIF(TRIM(EVIDENCIA_COMMIT_SHA), '') AS EVIDENCIA_COMMIT_SHA,
    NULLIF(TRIM(EVIDENCIA_ANEXO), '') AS EVIDENCIA_ANEXO,
    FATURA_ID,
    VALOR_FATURADO,
    TOTAL_UST,
    DATA_ULTIMA_ATUALIZACAO,
    USER_ABERTURA_ID,
    DATA_ABERTURA,
    APROVADA,
    USER_APROVADA_ID,
    ID_TAREFA_OLD,
    USER_ULTIMA_ATUALIZACAO_ID,
    TAREFA_PAI_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_TAREFA
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_TAREFAS_CENARIOS AS
SELECT
    ID,
    TAREFA_ID,
    CENARIO_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_TAREFAS_CENARIOS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_TECNOLOGIA AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    UNIDADE_ADM_ID,
    ID_TECNOLOGIA_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_TECNOLOGIA
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_TECNOLOGIAS_PROJETO AS
SELECT
    ID,
    PROJETO_ID,
    TECNOLOGIA_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_TECNOLOGIAS_PROJETO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_TIPO AS
SELECT
    ID,
    NULLIF(TRIM(NOME), '') AS NOME,
    UNIDADE_ADM_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_TIPO
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_TIPO_STATUS AS
SELECT
    ID,
    STATUS_ID,
    TIPO_ID,
    ID_TIPO_STATUS_OLD,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_TIPO_STATUS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_UNIDADE_ADM AS
SELECT
    ID,
    NULLIF(TRIM(NOME_UNIDADE), '') AS NOME_UNIDADE,
    NULLIF(TRIM(SIGLA), '') AS SIGLA,
    NULLIF(TRIM(RESPONSAVEL), '') AS RESPONSAVEL,
    NULLIF(TRIM(EMAIL), '') AS EMAIL,
    NULLIF(TRIM(TELEFONE), '') AS TELEFONE,
    CODIGO_SEI,
    UNIDADE_SUPERIOR_ID,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_UNIDADE_ADM
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW STG_UNIDADE_ADM_SUPERIOR AS
SELECT
    ID,
    NULLIF(TRIM(NOME_UNIDADE), '') AS NOME_UNIDADE,
    NULLIF(TRIM(SIGLA), '') AS SIGLA,
    NULLIF(TRIM(RESPONSAVEL), '') AS RESPONSAVEL,
    NULLIF(TRIM(EMAIL), '') AS EMAIL,
    NULLIF(TRIM(TELEFONE), '') AS TELEFONE,
    CODIGO_SEI,
    DW_BATCH_ID,
    DW_RECORD_SOURCE,
    DW_SOURCE_UPDATED_AT,
    DW_INGESTED_AT,
    DW_ROW_HASH
FROM MUNKA_RAW.RAW_UNIDADE_ADM_SUPERIOR
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DW_INGESTED_AT DESC, DW_SOURCE_UPDATED_AT DESC NULLS LAST) = 1;
