USE DATABASE DRAGON_DB;
USE SCHEMA MUNKA_RAW;

-- ============================================================================
-- 6. BRIDGES / TABELAS ASSOCIATIVAS
-- ============================================================================

CREATE OR REPLACE TABLE BRIDGE_USUARIO_ROLE AS
SELECT
    HASH('USUARIO', UR.USER_ID)                                AS SK_USUARIO,
    HASH('ROLE', UR.ROLE_ID)                                   AS SK_ROLE,
    UR.ID                                                      AS ID_ASSOCIACAO,
    UR.DW_INGESTED_AT                                          AS DT_CARGA
FROM STG_AB_USER_ROLE UR;

CREATE OR REPLACE TABLE BRIDGE_ROLE_PERMISSAO_MENU AS
SELECT
    HASH('ROLE', PVR.ROLE_ID)                                  AS SK_ROLE,
    HASH('PERMISSAO', PV.PERMISSION_ID)                        AS SK_PERMISSAO,
    HASH('MENU', PV.VIEW_MENU_ID)                              AS SK_MENU,
    PVR.ID                                                     AS ID_ASSOCIACAO,
    PVR.DW_INGESTED_AT                                         AS DT_CARGA
FROM STG_AB_PERMISSION_VIEW_ROLE PVR
JOIN STG_AB_PERMISSION_VIEW PV ON PV.ID = PVR.PERMISSION_VIEW_ID;

CREATE OR REPLACE TABLE BRIDGE_CONTRATO_USUARIO AS
SELECT HASH('CONTRATO', CONTRATO_ID) AS SK_CONTRATO,
       HASH('USUARIO', USUARIO_ID) AS SK_USUARIO,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_CONTRATOS_USUARIOS;

CREATE OR REPLACE TABLE BRIDGE_PROJETO_COORDENACAO AS
SELECT HASH('PROJETO', PROJETO_ID) AS SK_PROJETO,
       HASH('COORDENACAO', COORDENACAO_ID) AS SK_COORDENACAO,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_COORD_PROJETO;

CREATE OR REPLACE TABLE BRIDGE_PROJETO_LIDER AS
SELECT HASH('PROJETO', PROJETO_ID) AS SK_PROJETO,
       HASH('USUARIO', AB_USER_ID) AS SK_USUARIO,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_LIDER_PROJETOS;

CREATE OR REPLACE TABLE BRIDGE_PROJETO_ORIGEM AS
SELECT HASH('PROJETO', PROJETO_ID) AS SK_PROJETO,
       HASH('ORIGEM', ORIGEM_ID) AS SK_ORIGEM,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_ORIGENS_PROJETO;

CREATE OR REPLACE TABLE BRIDGE_PROJETO_TECNOLOGIA AS
SELECT HASH('PROJETO', PROJETO_ID) AS SK_PROJETO,
       HASH('TECNOLOGIA', TECNOLOGIA_ID) AS SK_TECNOLOGIA,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_TECNOLOGIAS_PROJETO;

CREATE OR REPLACE TABLE BRIDGE_PROJETO_RESULTADO_CHAVE AS
SELECT HASH('PROJETO', PROJETO_ID) AS SK_PROJETO,
       HASH('RESULTADO_CHAVE', RESULTADO_CHAVE_ID) AS SK_RESULTADO_CHAVE,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_PROJETO_RESULTADO_CHAVE;

CREATE OR REPLACE TABLE BRIDGE_PROJETO_FICHA AS
SELECT HASH('PROJETO', PROJETO_ID) AS SK_PROJETO,
       HASH('FICHA_INDICADOR', FICHA_ID) AS SK_FICHA_INDICADOR,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_FICHAS_PROJETOS;

CREATE OR REPLACE TABLE BRIDGE_TAREFA_CENARIO AS
SELECT HASH('TAREFA', TAREFA_ID) AS SK_TAREFA,
       HASH('CENARIO', CENARIO_ID) AS SK_CENARIO,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_TAREFAS_CENARIOS;

CREATE OR REPLACE TABLE BRIDGE_NIVEL_HIERARQUIA AS
SELECT HASH('NIVEL', NIVEL_SUPERIOR_ID) AS SK_NIVEL_SUPERIOR,
       HASH('NIVEL', NIVEL_INFERIOR_ID) AS SK_NIVEL_INFERIOR,
       ID AS ID_ASSOCIACAO,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_NIVEL_SUPERIOR;

CREATE OR REPLACE TABLE BRIDGE_TIPO_STATUS AS
SELECT HASH('TIPO', TIPO_ID) AS SK_TIPO,
       HASH('STATUS', STATUS_ID) AS SK_STATUS,
       ID AS ID_ASSOCIACAO,
       ID_TIPO_STATUS_OLD,
       DW_INGESTED_AT AS DT_CARGA
FROM STG_TIPO_STATUS;
