USE DATABASE DRAGON_DB;
USE SCHEMA MUNKA_RAW;

-- ============================================================================
-- 7. MARTS / CAMADA GOLD
-- ============================================================================

CREATE OR REPLACE VIEW MART_TAREFA_DETALHE AS
SELECT
    F.ID_TAREFA,
    F.NOME                                                     AS TAREFA,
    F.DESCRICAO,
    F.TIPO,
    F.NUM_HELPDESK,
    P.ID_PROJETO,
    P.NOME                                                     AS PROJETO,
    PR.ID_PRODUTO,
    PR.NOME                                                    AS PRODUTO,
    U.ID_USUARIO                                               AS ID_RESPONSAVEL,
    U.NOME_COMPLETO                                            AS RESPONSAVEL,
    C.NOME                                                     AS CARGO,
    N.NOME                                                     AS NIVEL,
    S.NOME                                                     AS STATUS,
    E.NOME                                                     AS ETIQUETA,
    SP.ID_SPRINT,
    SP.DESCRICAO_CURTA                                         AS SPRINT,
    F.DATA_ABERTURA,
    F.DATA_INICIO,
    F.DATA_FIM,
    F.DATA_ULTIMA_ATUALIZACAO,
    F.HORAS_EXECUTADAS,
    F.DURACAO_CALENDARIO_HORAS,
    F.TOTAL_UST,
    F.VALOR_FATURADO,
    F.FL_APROVADA,
    F.FL_EM_ABERTO,
    F.FL_POSSUI_EVIDENCIA,
    F.FL_EVIDENCIA_TEXTO,
    F.FL_EVIDENCIA_COMMIT,
    F.FL_EVIDENCIA_ANEXO,
    F.ID_FATURA
FROM FCT_TAREFA F
LEFT JOIN DIM_PROJETO P ON P.SK_PROJETO = F.SK_PROJETO
LEFT JOIN DIM_PRODUTO PR ON PR.SK_PRODUTO = F.SK_PRODUTO
LEFT JOIN DIM_USUARIO U ON U.SK_USUARIO = F.SK_RESPONSAVEL
LEFT JOIN DIM_CARGO C ON C.SK_CARGO = F.SK_CARGO
LEFT JOIN DIM_NIVEL N ON N.SK_NIVEL = F.SK_NIVEL
LEFT JOIN DIM_STATUS S ON S.SK_STATUS = F.SK_STATUS
LEFT JOIN DIM_ETIQUETA E ON E.SK_ETIQUETA = F.SK_ETIQUETA
LEFT JOIN DIM_SPRINT SP ON SP.SK_SPRINT = F.SK_SPRINT;

CREATE OR REPLACE VIEW MART_PROJETO_EXECUTIVO AS
SELECT
    D.ID_PROJETO,
    D.NOME                                                     AS PROJETO,
    D.PRODUTO,
    D.STATUS,
    D.NOME_UNIDADE,
    D.UNIDADE_SUPERIOR,
    D.DATA_SOLICITACAO,
    D.DATA_PREVISAO_INICIO,
    D.DATA_PREVISAO_TERMINO,
    D.DATA_PROD,
    D.PROGRESSO,
    F.FL_ATIVO,
    F.LEAD_TIME_DIAS,
    F.QUANTIDADE_TAREFAS,
    F.QUANTIDADE_TAREFAS_CONCLUIDAS,
    F.QUANTIDADE_TAREFAS_APROVADAS,
    IFF(F.QUANTIDADE_TAREFAS = 0, NULL,
        100.0 * F.QUANTIDADE_TAREFAS_CONCLUIDAS / F.QUANTIDADE_TAREFAS) AS PERCENTUAL_TAREFAS_CONCLUIDAS,
    F.PERCENTUAL_TAREFAS_COM_EVIDENCIA,
    F.HORAS_EXECUTADAS,
    F.TOTAL_UST,
    F.VALOR_FATURADO
FROM FCT_PROJETO F
JOIN DIM_PROJETO D ON D.SK_PROJETO = F.SK_PROJETO;

CREATE OR REPLACE VIEW MART_CONTRATO_FATURAMENTO AS
SELECT
    D.ID_CONTRATO,
    D.NOME                                                     AS CONTRATO,
    D.NOME_UNIDADE,
    D.DATA_INICIO,
    D.DATA_FIM,
    D.DATA_VIGENCIA,
    F.FL_ATIVO,
    F.UST_VALOR,
    F.UST_CONTRATADAS,
    F.UST_ADITIVADAS,
    F.TOTAL_UST_EXECUTADA,
    F.PERCENTUAL_UST_CONSUMIDA,
    F.TOTAL_HORAS_EXECUTADAS,
    F.TOTAL_VALOR_FATURADO,
    F.QUANTIDADE_TAREFAS,
    F.QUANTIDADE_FATURAS,
    (COALESCE(F.UST_CONTRATADAS, 0) + COALESCE(F.UST_ADITIVADAS, 0) - COALESCE(F.TOTAL_UST_EXECUTADA, 0)) AS SALDO_UST
FROM FCT_CONTRATO F
JOIN DIM_CONTRATO D ON D.SK_CONTRATO = F.SK_CONTRATO;

CREATE OR REPLACE VIEW MART_PRODUTIVIDADE_USUARIO AS
SELECT
    DATE_TRUNC('MONTH', F.DATA_FIM::DATE)                      AS MES_REFERENCIA,
    U.ID_USUARIO,
    U.NOME_COMPLETO                                            AS RESPONSAVEL,
    U.CARGO,
    U.NIVEL,
    U.COORDENACAO,
    COUNT(*)                                                   AS QUANTIDADE_TAREFAS,
    COUNT_IF(F.DATA_FIM IS NOT NULL)                           AS QUANTIDADE_CONCLUIDAS,
    COUNT_IF(F.FL_APROVADA)                                    AS QUANTIDADE_APROVADAS,
    COUNT_IF(F.FL_POSSUI_EVIDENCIA)                            AS QUANTIDADE_COM_EVIDENCIA,
    SUM(COALESCE(F.HORAS_EXECUTADAS, 0))                       AS HORAS_EXECUTADAS,
    SUM(COALESCE(F.TOTAL_UST, 0))                              AS TOTAL_UST,
    SUM(COALESCE(F.VALOR_FATURADO, 0))                         AS VALOR_FATURADO,
    IFF(SUM(COALESCE(F.HORAS_EXECUTADAS, 0)) = 0, NULL,
        SUM(COALESCE(F.TOTAL_UST, 0)) / SUM(COALESCE(F.HORAS_EXECUTADAS, 0))) AS UST_POR_HORA
FROM FCT_TAREFA F
LEFT JOIN DIM_USUARIO U ON U.SK_USUARIO = F.SK_RESPONSAVEL
GROUP BY 1, 2, 3, 4, 5, 6;

CREATE OR REPLACE VIEW MART_EVIDENCIA_LM AS
WITH COMENTARIOS AS (
    SELECT
        TAREFA_ID,
        LISTAGG(CONTEUDO, '\n') WITHIN GROUP (ORDER BY HORARIO) AS TEXTO_COMENTARIOS,
        COUNT(*)                                                AS QUANTIDADE_COMENTARIOS
    FROM STG_COMENTARIO
    GROUP BY TAREFA_ID
), CENARIOS AS (
    SELECT
        TC.TAREFA_ID,
        LISTAGG(C.NOME, ' | ') WITHIN GROUP (ORDER BY C.NOME)   AS CENARIOS,
        SUM(COALESCE(C.PONTUACAO, 0))                           AS PONTUACAO_CENARIOS
    FROM STG_TAREFAS_CENARIOS TC
    JOIN STG_CENARIO C ON C.ID = TC.CENARIO_ID
    GROUP BY TC.TAREFA_ID
)
SELECT
    T.ID                                                       AS ID_TAREFA,
    T.NOME                                                     AS TAREFA,
    T.DESCRICAO,
    T.EVIDENCIAS,
    T.EVIDENCIA_COMMIT_SHA,
    T.EVIDENCIA_ANEXO,
    COALESCE(CO.TEXTO_COMENTARIOS, '')                         AS COMENTARIOS,
    COALESCE(CO.QUANTIDADE_COMENTARIOS, 0)                     AS QUANTIDADE_COMENTARIOS,
    CE.CENARIOS,
    CE.PONTUACAO_CENARIOS,
    P.NOME                                                     AS PROJETO,
    PR.NOME                                                    AS PRODUTO,
    S.NOME                                                     AS STATUS,
    U.NOME_COMPLETO                                            AS RESPONSAVEL,
    R.SERVICO,
    R.COMPLEXIDADE,
    R.CARGO,
    R.NIVEL,
    T.HORAS_EXECUTADAS,
    T.TOTAL_UST,
    T.VALOR_FATURADO,
    T.APROVADA                                                 AS LABEL_APROVADA,
    IFF(T.DATA_FIM IS NOT NULL, TRUE, FALSE)                   AS LABEL_CONCLUIDA,
    REGEXP_REPLACE(CONCAT_WS('\n',
        'TAREFA: ' || COALESCE(T.NOME, ''),
        'DESCRICAO: ' || COALESCE(T.DESCRICAO, ''),
        'EVIDENCIA: ' || COALESCE(T.EVIDENCIAS, ''),
        'COMMIT: ' || COALESCE(T.EVIDENCIA_COMMIT_SHA, ''),
        'ANEXO: ' || COALESCE(T.EVIDENCIA_ANEXO, ''),
        'COMENTARIOS: ' || COALESCE(CO.TEXTO_COMENTARIOS, ''),
        'CENARIOS: ' || COALESCE(CE.CENARIOS, '')
    ), '<[^>]+>', ' ')                                        AS TEXTO_MODELO,
    REGEXP_COUNT(TRIM(CONCAT_WS(' ', T.DESCRICAO, T.EVIDENCIAS, CO.TEXTO_COMENTARIOS)), '\\S+') AS QUANTIDADE_PALAVRAS,
    REGEXP_COUNT(LOWER(CONCAT_WS(' ', T.EVIDENCIAS, T.EVIDENCIA_ANEXO)), 'https?://') AS QUANTIDADE_URLS,
    IFF(REGEXP_LIKE(LOWER(COALESCE(T.EVIDENCIA_ANEXO, '')), '\\.(png|jpg|jpeg|gif|webp|bmp|svg)(\\?|$)'), TRUE, FALSE) AS FL_POSSUI_IMAGEM,
    IFF(NULLIF(TRIM(T.EVIDENCIA_COMMIT_SHA), '') IS NOT NULL, TRUE, FALSE) AS FL_POSSUI_COMMIT,
    T.DATA_ULTIMA_ATUALIZACAO
FROM STG_TAREFA T
LEFT JOIN DIM_PROJETO P ON P.ID_PROJETO = T.PROJETO_ID
LEFT JOIN DIM_PRODUTO PR ON PR.ID_PRODUTO = T.PRODUTO_ID
LEFT JOIN DIM_STATUS S ON S.ID_STATUS = T.STATUS_ID
LEFT JOIN DIM_USUARIO U ON U.ID_USUARIO = T.RESPONSAVEL_ID
LEFT JOIN DIM_REGRA R ON R.ID_REGRA = T.REGRA_ID
LEFT JOIN COMENTARIOS CO ON CO.TAREFA_ID = T.ID
LEFT JOIN CENARIOS CE ON CE.TAREFA_ID = T.ID;

CREATE OR REPLACE VIEW MART_SEGURANCA_ACESSO AS
SELECT
    U.ID_USUARIO,
    U.NOME_COMPLETO,
    U.USERNAME,
    U.FL_ATIVO,
    R.ID_ROLE,
    R.NOME                                                     AS ROLE,
    P.ID_PERMISSAO,
    P.NOME                                                     AS PERMISSAO,
    M.ID_MENU,
    M.NOME                                                     AS MENU
FROM BRIDGE_USUARIO_ROLE UR
JOIN DIM_USUARIO U ON U.SK_USUARIO = UR.SK_USUARIO
JOIN DIM_ROLE R ON R.SK_ROLE = UR.SK_ROLE
LEFT JOIN BRIDGE_ROLE_PERMISSAO_MENU RPM ON RPM.SK_ROLE = R.SK_ROLE
LEFT JOIN DIM_PERMISSAO P ON P.SK_PERMISSAO = RPM.SK_PERMISSAO
LEFT JOIN DIM_MENU M ON M.SK_MENU = RPM.SK_MENU;

CREATE OR REPLACE VIEW CTL_VERSAO_ORIGEM AS
SELECT VERSION_NUM AS VERSAO_ALEMBIC, DW_INGESTED_AT AS DT_CARGA
FROM STG_ALEMBIC_VERSION;
