USE DATABASE DRAGON_DB;
USE SCHEMA MUNKA;

-- ============================================================================
-- 8. QUALIDADE DE DADOS
-- ============================================================================

CREATE OR REPLACE VIEW DQ_TAREFA_CHAVES_INVALIDAS AS
SELECT *
FROM (
    SELECT
        T.ID                                                       AS ID_TAREFA,
        IFF(T.PROJETO_ID IS NOT NULL AND P.ID IS NULL, TRUE, FALSE) AS ERRO_PROJETO,
        IFF(T.PRODUTO_ID IS NOT NULL AND PR.ID IS NULL, TRUE, FALSE) AS ERRO_PRODUTO,
        IFF(T.RESPONSAVEL_ID IS NOT NULL AND U.ID IS NULL, TRUE, FALSE) AS ERRO_RESPONSAVEL,
        IFF(T.STATUS_ID IS NOT NULL AND S.ID IS NULL, TRUE, FALSE) AS ERRO_STATUS,
        IFF(T.REGRA_ID IS NOT NULL AND R.ID IS NULL, TRUE, FALSE)  AS ERRO_REGRA,
        IFF(T.FATURA_ID IS NOT NULL AND F.ID IS NULL, TRUE, FALSE) AS ERRO_FATURA
    FROM STG_TAREFA T
    LEFT JOIN STG_PROJETO P ON P.ID = T.PROJETO_ID
    LEFT JOIN STG_PRODUTO PR ON PR.ID = T.PRODUTO_ID
    LEFT JOIN STG_AB_USER U ON U.ID = T.RESPONSAVEL_ID
    LEFT JOIN STG_STATUS S ON S.ID = T.STATUS_ID
    LEFT JOIN STG_REGRA R ON R.ID = T.REGRA_ID
    LEFT JOIN STG_FATURA F ON F.ID = T.FATURA_ID
) Q
WHERE ERRO_PROJETO OR ERRO_PRODUTO OR ERRO_RESPONSAVEL
   OR ERRO_STATUS OR ERRO_REGRA OR ERRO_FATURA;

CREATE OR REPLACE VIEW DQ_TAREFA_SEM_EVIDENCIA AS
SELECT
    ID,
    NOME,
    PROJETO_ID,
    RESPONSAVEL_ID,
    STATUS_ID,
    DATA_FIM,
    APROVADA
FROM STG_TAREFA
WHERE DATA_FIM IS NOT NULL
  AND NULLIF(TRIM(EVIDENCIAS), '') IS NULL
  AND NULLIF(TRIM(EVIDENCIA_COMMIT_SHA), '') IS NULL
  AND NULLIF(TRIM(EVIDENCIA_ANEXO), '') IS NULL;

CREATE OR REPLACE VIEW DQ_RESUMO AS
SELECT 'TAREFA_CHAVES_INVALIDAS' AS REGRA, COUNT(*) AS QUANTIDADE FROM DQ_TAREFA_CHAVES_INVALIDAS
UNION ALL
SELECT 'TAREFA_CONCLUIDA_SEM_EVIDENCIA', COUNT(*) FROM DQ_TAREFA_SEM_EVIDENCIA
UNION ALL
SELECT 'TAREFA_SEM_RESPONSAVEL', COUNT(*) FROM STG_TAREFA WHERE RESPONSAVEL_ID IS NULL
UNION ALL
SELECT 'TAREFA_HORAS_NEGATIVAS', COUNT(*) FROM STG_TAREFA WHERE HORAS_EXECUTADAS < 0
UNION ALL
SELECT 'PROJETO_PROGRESSO_INVALIDO', COUNT(*) FROM STG_PROJETO WHERE PROGRESSO < 0 OR PROGRESSO > 100;

-- ============================================================================
-- 9. CONSULTAS DE VALIDAÇÃO
-- ============================================================================
-- SELECT * FROM DQ_RESUMO;
-- SELECT * FROM MART_PROJETO_EXECUTIVO ORDER BY PROGRESSO DESC;
-- SELECT * FROM MART_CONTRATO_FATURAMENTO ORDER BY PERCENTUAL_UST_CONSUMIDA DESC;
-- SELECT * FROM MART_EVIDENCIA_LM LIMIT 100;
-- SELECT COUNT(*) FROM FCT_TAREFA;

-- ============================================================================
-- 10. ORDEM DE EXECUÇÃO NO PIPELINE
-- ============================================================================
-- 1) Executar a criação de CTL_ e RAW_ uma única vez.
-- 2) Carregar RAW_ via Airflow, Fivetran, DMS, COPY ou conector PostgreSQL.
-- 3) Recriar STG_, DIM_, FCT_, BRIDGE_, MART_ e DQ_ após cada carga.
-- 4) Para produção com histórico, substituir CREATE OR REPLACE TABLE das dimensões
--    por MERGE/SCD2 ou modelos incrementais do dbt.
